### ISSUE TITLE
Use tree-sitter

### ISSUE THREAD

**Issue by lopi-py** [Darazaki/indent-o-matic#16]
it should accurate comments and strings when working with treesitter as it disables syntax so the current function to detect it wont work

**Comment by Darazaki** [comment]
Thanks for telling me! I'll take a look at this tomorrow :)

Since I'm currently very busy, fixing this might take a while. So if you have any example of code or a function in the documentation that could be used to check if a character's position is included in a comment/string please link it here. That'd be extremely helpful!

Labeling this issue as a bug since this plugin should work both with tree-sitter and without

**Comment by lopi-py** [comment]
I found one [implementation](https://github.com/hrsh7th/nvim-cmp/blob/0e436ee23abc6c3fe5f3600145d2a413703e7272/lua/cmp/config/context.lua) that fits, also keep an eye at this functions: [1](https://github.com/nvim-treesitter/nvim-treesitter/blob/5d11dfc27849e3d7435c32dbd8ea9be35bcd990b/lua/nvim-treesitter/ts_utils.lua#L188), [2](https://github.com/nvim-treesitter/nvim-treesitter/blob/5d11dfc27849e3d7435c32dbd8ea9be35bcd990b/lua/nvim-treesitter/ts_utils.lua#L157). Also keep in mind that second function returns like `root:named_descendant_for_range(...)` so you can use it as
```lua
return result:type() == "comment" or result:type() == "string"`
```

**Comment by Darazaki** [comment]
Thanks a lot! These have really helped :D

I think I've finished fixing this issue inside the `testing` branch. I'll do some more testing and should push the fix tomorrow :)
