### ISSUE TITLE
Integrate with nvim native editorconfig

### ISSUE THREAD

**Issue by meijieru** [Darazaki/indent-o-matic#21]
Editorconfig is now a native feature of nvim nightly.
It would be great if the plugin could be compatible with it, in which this plugin only takes effect when the editorconfig doesn't set the configs.

**Comment by Darazaki** [comment]
I didn't know that, thanks for telling me!

I'll take a look at it this Thursday to see if there's any already available API to know if a buffer's indentation is controlled by EditorConfig and hopefully push a new indent-o-matic version then :)

Assuming this goes well, do you think indentation detection should be disabled by default if EditorConfig is already active? (This will probably be an option but since I don't use EditorConfig I don't know what people would expect to be the default)

**Comment by meijieru** [comment]
> Assuming this goes well, do you think indentation detection should be disabled by default if EditorConfig is already active? 

I think so. And you can check which options are set by editorconfig by `vim.b.editorconfig`.

**Comment by Darazaki** [comment]
Wow, this should be pretty straightforward then! Thanks a lot :)

**Comment by meijieru** [comment]
I used it together already for a while. Seems no problem.
